// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIcqitpMf5ftWPVhfSJ6I87d_oC0b5Go0',
    appId: '1:334119315414:web:8b621bb95352d6243c2677',
    messagingSenderId: '334119315414',
    projectId: 'fastfood-app-9a3fa',
    authDomain: 'fastfood-app-9a3fa.firebaseapp.com',
    databaseURL: 'https://fastfood-app-9a3fa-default-rtdb.firebaseio.com',
    storageBucket: 'fastfood-app-9a3fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJSMWQEoE2I3t62bJtWmJRmscIslZq_Y',
    appId: '1:334119315414:android:eb4284e950a818333c2677',
    messagingSenderId: '334119315414',
    projectId: 'fastfood-app-9a3fa',
    databaseURL: 'https://fastfood-app-9a3fa-default-rtdb.firebaseio.com',
    storageBucket: 'fastfood-app-9a3fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP3ZA9CHCdMKBedX_1tM1AYRkSFVV4G60',
    appId: '1:334119315414:ios:153b3697bc83bd163c2677',
    messagingSenderId: '334119315414',
    projectId: 'fastfood-app-9a3fa',
    databaseURL: 'https://fastfood-app-9a3fa-default-rtdb.firebaseio.com',
    storageBucket: 'fastfood-app-9a3fa.firebasestorage.app',
    iosBundleId: 'com.example.fastfoodAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP3ZA9CHCdMKBedX_1tM1AYRkSFVV4G60',
    appId: '1:334119315414:ios:153b3697bc83bd163c2677',
    messagingSenderId: '334119315414',
    projectId: 'fastfood-app-9a3fa',
    databaseURL: 'https://fastfood-app-9a3fa-default-rtdb.firebaseio.com',
    storageBucket: 'fastfood-app-9a3fa.firebasestorage.app',
    iosBundleId: 'com.example.fastfoodAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIcqitpMf5ftWPVhfSJ6I87d_oC0b5Go0',
    appId: '1:334119315414:web:cb250d4a8b909bc13c2677',
    messagingSenderId: '334119315414',
    projectId: 'fastfood-app-9a3fa',
    authDomain: 'fastfood-app-9a3fa.firebaseapp.com',
    databaseURL: 'https://fastfood-app-9a3fa-default-rtdb.firebaseio.com',
    storageBucket: 'fastfood-app-9a3fa.firebasestorage.app',
  );
}
